// const

import { MovieQueryOptionsV2, TvShowQueryOptionsV2 } from '@/lib/patch';

export const DB_LOCALE = 'en';
export const REGION = 'US';

// objects

export const movieSearchObject: MovieQueryOptionsV2 = {
  language: undefined,
  sort_by: 'popularity.desc',
  page: 1,
  'vote_average.gte': undefined,
  'vote_count.gte': undefined,
  'vote_count.lte': undefined,
  'vote_average.lte': undefined,
  with_watch_providers: undefined,
  watch_region: undefined,
  without_companies: undefined,
  with_watch_monetization_types: undefined,
  'with_runtime.gte': undefined,
  'with_runtime.lte': undefined,
  with_genres: undefined,
  without_genres: undefined,
  with_original_language: undefined,
  with_origin_country: undefined,
  without_keywords: undefined,
  with_keywords: undefined,
  with_companies: undefined,
  include_adult: false,
  region: undefined,
  certification_country: REGION,
  certification: undefined,
  'certification.lte': undefined,
  'certification.gte': undefined,
  include_video: false,
  primary_release_year: undefined,
  'primary_release_date.gte': undefined,
  'primary_release_date.lte': undefined,
  'release_date.gte': undefined,
  'release_date.lte': undefined,
  with_release_type: undefined,
  year: undefined,
  with_cast: undefined,
  with_crew: undefined,
  with_people: undefined,
};

export const tvSearchObject: TvShowQueryOptionsV2 = {
  language: undefined,
  sort_by: 'popularity.desc',
  page: 1,
  'vote_average.gte': undefined,
  'vote_count.gte': undefined,
  'vote_count.lte': undefined,
  'vote_average.lte': undefined,
  with_watch_providers: undefined,
  watch_region: undefined,
  without_companies: undefined,
  with_watch_monetization_types: undefined,
  'with_runtime.gte': undefined,
  'with_runtime.lte': undefined,
  with_genres: undefined,
  without_genres: undefined,
  with_original_language: undefined,
  with_origin_country: undefined,
  without_keywords: undefined,
  with_keywords: undefined,
  with_companies: undefined,
  include_adult: false,
  'air_date.gte': undefined,
  'air_date.lte': undefined,
  'first_air_date.gte': undefined,
  'first_air_date.lte': undefined,
  first_air_date_year: undefined,
  timezone: undefined,
  with_networks: undefined,
  include_null_first_air_dates: false,
  screened_theatrically: undefined,
  with_status: undefined,
  with_type: undefined,
};
